wave:
  form: tirangle
  zero: 0
  amp: 500
  N: 1000
settings:
  delta-fine: 10 # (mT) WIP delta for PID-enable
  delta-start: 1 # (mT) delta to start measure
  max-inc: 5  # (mT) set field delta
  wait-b: 0.5  # (s) wait until next iteration
  timeout: 20  # (s) until field reached
lockin:
  f: 833.33
