data:
  path: ''
  sample: ''
  comment: ''
wave:
  form: tirangle
  zero: 0 # (p.u.) const. field before and after wave
  offset: 0 # (mT) offset of the B-field
  amp: 10 # (mT) amplitude of the B-field
  N: 100 # number of points in the B-field vector
settings:
  delta-fine: 10 # (mT) WIP delta for PID-enable
  delta-start: 1 # (mT) delta to start measure i.e. wait until error >= delta-start
  max-inc: 2  # (mT) set field delta
  wait-b: 0.5  # (s) wait until next iteration
  timeout: 20  # (s) until field reached
  bruker-const: 0.8 # (s/mT) time-constant of the main coils
  f: 833.33 # (Hz) Lock-In output frequency
  max-field: 1000 # (mT) maximum applicable B-field 
  min-field: -10 # (mT) minimum applicable B-field
