import numpy as np
import logging

class LookupFit:
    """Provide an interface to a fit-function generated by a set of measured values.
        
    Args: 
        x (Array):     array representing the x-axis
        y (Array):	array representing the y-axis
    	deg(int):	polynomial degree to fit. Defaults to 1
    """
    def __init__(self, x, y, deg=1):
        self._x = np.array(x)
        self._y = np.array(y)

        if not self._x.shape == self._y.shape:
            raise ValueError("Array shapes do not match")

        self._deg = deg
        self._co = np.polyfit(self._x, self._y, self._deg)
        self._func = np.poly1d(self._co)

    def getValue(self, v):
        """Return a corresponding y-axis value based on the provided x-axis value.

        Args:
            v (num):	x-value
        """
        return  self._func(v)



class LinearFit:
    """Linear scale Lookup function.
    
    Args: 
    	scale (num):	scale factor
    """
    def  __init__(self, _scale = 0):
        self.scale = _scale

    def scaler(self, v):
        """Scales with the scale property.

            Args:
                _v (num, array):	value to be scaled
        """
        return self.scale * v
    
