import numpy as np
import logging

class LookupFit:
    """Provide an interface to a fit-function generated by a set of measured values.
        
    Args: 
        _x (Array):     array representing the x-axis
        _y (Array):	array representing the y-axis
    	_deg(int):	polynomial degree to fit
    """
    def __init__(self, _x, _y, _deg=0):
        self.x = np.array(_x)
        self.y = np.array(_y)

        if not self.x.shape == self.y.shape:
            raise ValueError("Array shapes do not match")

        self.deg = _deg
        self.co = np.polyfit(self.x, self.y, self.deg)
        self.func = np.poly1d(self.co)

    def getValue(self, _v):
        """Return a corresponding y-axis value based on the provided x-axis value.

        Args:
            _v (number):	x-value
        """
        return  self.func(_v)
